name: Server
on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docker_image: ${{ steps.build-and-push.imageid }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}

      - name: Log into registry ${{ env.DOCKER_REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    env:
      TF_VAR_server_image: ${{ build.docker_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run: |
          terraform init \
            -backend-config="access_key=${{ env.AWS_ACCESS_KEY_ID }}" \
            -backend-config="secret_key=${{ env.AWS_SECRET_KEY }}" \
            -backend-config="bucket=${{ env.AWS_BACKEND_BUCKET }}"

      - name: Check if config has proper formatting
        run: terraform fmt -check

      - name: Check if config is valid
        run: terraform validate -no-color

      - name: Display plan
        run: terraform plan

      - name: Apply configuration
        run: terraform apply -auto-approve
