name: nginx server
on: [push]
env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE: $DOCKER_REGISTRY/grim_yawn/simple-server-aws
  DOCKER_IMAGE_TAG: $GITHUB_SHA
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }} .
